version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels
