version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels
    groups:
      primevue:
        patterns:
          - "primevue"
          - "@primevue/*"
      nuxt:
        patterns:
          - "nuxt"
          - "@nuxt/*"
          - "nuxt-*"
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "primevue"
          - "@primevue/*"
          - "nuxt"
          - "@nuxt/*"
          - "nuxt-*"

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels
    groups:
      aspire:
        patterns:
          - "Aspire.*"
      dotnet-analyzers:
        patterns:
          - "Meziantou.Analyzer"
          - "CSharpier.*"
      efcore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Npgsql.EntityFrameworkCore*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Europe/Brussels
