// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shoplists.Persistence;

#nullable disable

namespace Shoplists.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407164049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shoplists.Domain.Models.Shoplists.Shoplist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Shoplists");
                });

            modelBuilder.Entity("Shoplists.Domain.Models.Shoplists.ShoplistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShoplistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShoplistId");

                    b.ToTable("ShoplistItem");
                });

            modelBuilder.Entity("Shoplists.Domain.Models.Shoplists.ShoplistItem", b =>
                {
                    b.HasOne("Shoplists.Domain.Models.Shoplists.Shoplist", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoplistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoplists.Domain.Models.Shoplists.Shoplist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
